### ISSUE TITLE
[Bug]: python3 -m pagermaid 執行錯誤

### ISSUE THREAD

**Issue by liups233** [TeamPGM/PagerMaid-Pyro#30]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### PagerMaid 版本 （或 Commit Id）

9de5f56

### 运行环境

Debian 11 - 5.10.0-17-amd64

### 运行架构

AMD64

### 重现步骤

```
cd ~ && git clone https://github.com/TeamPGM/PagerMaid-Pyro.git pagermaid
sudo apt install neofetch libzbar-dev -y 
sudo mv ~/pagermaid /opt/ && cd /opt/pagermaid
sudo useradd pagermaid
sudo chown -R pagermaid:pagermaid /opt/pagermaid
sudo pip3 install -r /opt/pagermaid/requirements.txt
sudo -u pagermaid bash
cp config.gen.yml config.yml
<修改config.yml中的id hash>
python3 -m pagermaid # ----> 出錯


```

### 期望的结果是什么？

正確登入帳號

### 实际的结果是什么？

python3 -m pagermaid 執行錯誤

### 日志记录（可选）

```python3
pagermaid@Debian-ESXi:/opt/pagermaid$ python3 -m pagermaid
[Degrade] Reading alias file failed：[Errno 2] No such file or directory: 'data/alias.json'
INFO [2022-09-07 08:56:40] [pagermaid] 加载内置模块: account, avoid, backup, clock, help, message, mixpanel, plugin, prune, reload, sentry, status, sudo, system, update
INFO [2022-09-07 08:56:40] [pagermaid] 将平台检测为“linux”，进入PagerMaid的早期加载过程。
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/pagermaid/pagermaid/__main__.py", line 46, in <module>
    bot.run(main())
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/utilities/run.py", line 77, in run
    run(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/pagermaid/pagermaid/__main__.py", line 19, in main
    await bot.start()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/client.py", line 584, in load_session
    await Auth(
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/auth.py", line 261, in create
    self.connection.close()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/connection/connection.py", line 76, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

### 补充说明（可选）

- 本人將pagermaid置於/opt/pagermaid下，權限分給新建使用者pagermaid，使用sudo -u pagermaid bash後執行
- pythonu 依賴使用sudo安裝

**Comment by omg-xtao** [comment]
尝试删除目录下 `pagermaid.session` 重新运行

**Comment by liups233** [comment]
> 

沒有成功，錯誤依舊

**Comment by omg-xtao** [comment]
无法连接至 TG 服务器，尝试更换服务器

**Comment by liups233** [comment]
> 无法连接至 TG 服务器，尝试更换服务器

vps是香港的

**Comment by Code-Dramatist** [comment]
这个问题已解决
