### ISSUE TITLE
docker-compose.yml 搭建报错，无法运行！  [Bug]: OSError: [Errno 18] Invalid cross-device link: 'config.yml' -> 'data/config.yml'

### ISSUE THREAD

**Issue by tracy1949** [TeamPGM/PagerMaid-Pyro#74]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

PagerMaid-Pyro

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 导致错误的插件是什么？

docker-compose.yml

version: "2.0"
services:
  pagermaid:
    image: teampgm/pagermaid_pyro
    restart: always
    container_name: PagerMaid-Pyro
    hostname: pagermaid
    ports:                 
      - "3333:3333"
    volumes:
      - ./data:/pagermaid/workdir/data
    environment:
      - WEB_ENABLE=true
      - WEB_SECRET_KEY=sfwefwe23
      - WEB_HOST=0.0.0.0
      - WEB_PORT=3333

### 重现步骤

OSError: [Errno 18] Invalid cross-device link: 'config.yml' -> 'data/config.yml'

### 期望的结果是什么？

OSError: [Errno 18] Invalid cross-device link: 'config.yml' -> 'data/config.yml'

### 实际的结果是什么？

OSError: [Errno 18] Invalid cross-device link: 'config.yml' -> 'data/config.yml'

### 日志记录（可选）

```python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/pagermaid/workdir/pagermaid/__init__.py", line 19, in <module>
    import pagermaid.update
  File "/pagermaid/workdir/pagermaid/update/__init__.py", line 5, in <module>
    __import__(file, globals(), level=1)
  File "/pagermaid/workdir/pagermaid/update/v1402.py", line 22, in <module>
    rename(config)
  File "/pagermaid/workdir/pagermaid/update/v1402.py", line 13, in rename
    old.rename(new)
  File "/usr/lib/python3.10/pathlib.py", line 1234, in rename
    self._accessor.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: 'config.yml' -> 'data/config.yml'
```

**Comment by tracy1949** [comment]
**docker-compose.yml 拉取镜像后无法启动，日志报错：OSError: [Errno 18] Invalid cross-device link: 'config.yml' -> 'data/config.yml'**
